"""SQLAlchemy 2.0 models mirroring migrations/0001_init.sql.

Per docs/DECISIONS.md ADR-007, these are hand-kept in sync with the SQL
migrations, not autogenerated -- the migrations are the source of truth
for the actual schema (applied by scripts/migrate.py against Postgres in
production); these models are how the control plane reads/writes that
same schema, and (via SQLite in tests, see tests/conftest.py) how the
test suite exercises real query logic without requiring a live Postgres.

IDs are generated in Python (uuid4-based, prefixed by entity type) rather
than relying on Postgres's server-side gen_random_uuid() default, so the
same model code produces valid rows against both Postgres and SQLite.
"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone

from sqlalchemy import (
    JSON,
    BigInteger,
    Boolean,
    DateTime,
    ForeignKey,
    Integer,
    Numeric,
    String,
    Text,
    UniqueConstraint,
)
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship


def _now() -> datetime:
    return datetime.now(timezone.utc)


def _id(prefix: str) -> str:
    return f"{prefix}_{uuid.uuid4().hex}"


# BIGSERIAL on Postgres (matching migrations/0001_init.sql), plain
# INTEGER on SQLite -- SQLite only auto-increments a bare `INTEGER
# PRIMARY KEY` (its rowid alias); a BIGINT primary key does NOT get
# autoincrement behavior there, so a straight BigInteger column would
# fail every insert under the test suite's SQLite backend with a NOT
# NULL constraint violation on `id`.
_AutoBigInt = BigInteger().with_variant(Integer, "sqlite")


class Base(DeclarativeBase):
    pass


class Tenant(Base):
    __tablename__ = "tenants"

    id: Mapped[str] = mapped_column(String, primary_key=True, default=lambda: _id("tenant"))
    name: Mapped[str] = mapped_column(String, unique=True, nullable=False)
    openai_org_id: Mapped[str | None] = mapped_column(String, nullable=True)
    anthropic_workspace_id: Mapped[str | None] = mapped_column(String, nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_now)

    agents: Mapped[list["Agent"]] = relationship(back_populates="tenant", cascade="all, delete-orphan")
    api_keys: Mapped[list["ApiKey"]] = relationship(back_populates="tenant", cascade="all, delete-orphan")
    budgets: Mapped[list["Budget"]] = relationship(back_populates="tenant", cascade="all, delete-orphan")


class Agent(Base):
    __tablename__ = "agents"
    __table_args__ = (UniqueConstraint("tenant_id", "name", name="uq_agents_tenant_name"),)

    id: Mapped[str] = mapped_column(String, primary_key=True, default=lambda: _id("agent"))
    tenant_id: Mapped[str] = mapped_column(ForeignKey("tenants.id", ondelete="CASCADE"), nullable=False)
    name: Mapped[str] = mapped_column(String, nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_now)

    tenant: Mapped[Tenant] = relationship(back_populates="agents")


class ApiKey(Base):
    __tablename__ = "api_keys"

    id: Mapped[str] = mapped_column(String, primary_key=True, default=lambda: _id("key"))
    tenant_id: Mapped[str] = mapped_column(ForeignKey("tenants.id", ondelete="CASCADE"), nullable=False)
    # Set only for scope=["agent"] keys minted by POST /v1/agents -- see
    # migrations/0001_init.sql for the full rationale.
    agent_id: Mapped[str | None] = mapped_column(ForeignKey("agents.id", ondelete="CASCADE"), nullable=True)
    key_prefix: Mapped[str] = mapped_column(String, nullable=False, index=True)
    hashed_key: Mapped[str] = mapped_column(String, nullable=False)
    # JSON array of scope strings (e.g. ["admin","agent"]) -- see
    # migrations/0001_init.sql for why this is JSON/JSONB rather than a
    # native Postgres TEXT[]: it's portable to SQLite for this service's
    # test suite, and the Go gateway's internal/auth parses it the same
    # way with encoding/json.
    scopes: Mapped[list[str]] = mapped_column(JSON, nullable=False)
    label: Mapped[str | None] = mapped_column(String, nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_now)
    revoked_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    tenant: Mapped[Tenant] = relationship(back_populates="api_keys")


class Budget(Base):
    __tablename__ = "budgets"
    __table_args__ = (
        UniqueConstraint("tenant_id", "agent_id", "task_id", name="uq_budgets_scope"),
    )

    id: Mapped[str] = mapped_column(String, primary_key=True, default=lambda: _id("budget"))
    tenant_id: Mapped[str] = mapped_column(ForeignKey("tenants.id", ondelete="CASCADE"), nullable=False)
    agent_id: Mapped[str | None] = mapped_column(ForeignKey("agents.id", ondelete="CASCADE"), nullable=True)
    task_id: Mapped[str | None] = mapped_column(String, nullable=True)
    token_limit: Mapped[int | None] = mapped_column(BigInteger, nullable=True)
    dollar_limit: Mapped[float | None] = mapped_column(Numeric(12, 6), nullable=True)
    refill_rate_per_min: Mapped[float] = mapped_column(Numeric(14, 4), nullable=False, default=0)
    period_seconds: Mapped[int] = mapped_column(BigInteger, nullable=False, default=86400)
    updated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_now, onupdate=_now)

    tenant: Mapped[Tenant] = relationship(back_populates="budgets")


class SpendEvent(Base):
    __tablename__ = "spend_events"

    id: Mapped[int] = mapped_column(_AutoBigInt, primary_key=True, autoincrement=True)
    tenant_id: Mapped[str] = mapped_column(ForeignKey("tenants.id", ondelete="CASCADE"), nullable=False, index=True)
    agent_id: Mapped[str | None] = mapped_column(String, nullable=True)
    task_id: Mapped[str | None] = mapped_column(String, nullable=True)
    model: Mapped[str] = mapped_column(String, nullable=False)
    tokens_in: Mapped[int] = mapped_column(BigInteger, nullable=False, default=0)
    tokens_out: Mapped[int] = mapped_column(BigInteger, nullable=False, default=0)
    cost_usd: Mapped[float] = mapped_column(Numeric(14, 8), nullable=False, default=0)
    trace_id: Mapped[str] = mapped_column(String, nullable=False)
    decision: Mapped[str] = mapped_column(String, nullable=False)
    decision_reason: Mapped[str] = mapped_column(String, nullable=False, default="")
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_now, index=True)


class ReconciliationRun(Base):
    __tablename__ = "reconciliation_runs"

    id: Mapped[int] = mapped_column(_AutoBigInt, primary_key=True, autoincrement=True)
    started_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_now)
    completed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    window_start: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    window_end: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    drift_detected: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    drift_amount_usd: Mapped[float] = mapped_column(Numeric(14, 6), nullable=False, default=0)
    error: Mapped[str | None] = mapped_column(Text, nullable=True)


class ReconciliationDrift(Base):
    __tablename__ = "reconciliation_drift"

    id: Mapped[int] = mapped_column(_AutoBigInt, primary_key=True, autoincrement=True)
    run_id: Mapped[int] = mapped_column(ForeignKey("reconciliation_runs.id", ondelete="CASCADE"), nullable=False)
    tenant_id: Mapped[str] = mapped_column(ForeignKey("tenants.id", ondelete="CASCADE"), nullable=False, index=True)
    gateway_observed_usd: Mapped[float] = mapped_column(Numeric(14, 6), nullable=False)
    provider_reported_usd: Mapped[float] = mapped_column(Numeric(14, 6), nullable=False)
    drift_amount_usd: Mapped[float] = mapped_column(Numeric(14, 6), nullable=False)
    drift_pct: Mapped[float] = mapped_column(Numeric(7, 4), nullable=False)
    resolved_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_now)
